version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    cooldown:
      default-days: 1
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '>=25.0.0'
    groups:
      major-updates:
        update-types:
          - major
      production-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    commit-message:
      prefix: ci
      include: scope
    cooldown:
      default-days: 1
    groups:
      github-actions:
        patterns:
          - '*'
